config/routes.rb
Mightyboy::Application.routes.draw do

  get "items/index"
  get "cart/show", as: 'cart'
   root 'static_pages#index'
   resources :orders, only: [:update, :create, :destroy]
   get 'catering', to: 'catering#new', as: 'contact'
   get 'catering', to: 'catering#index', as: 'catering'
   post 'catering', to: 'catering#create'

end

app/models/catering.rb
class Catering < ActiveRecord::Base
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :message

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :message,
    presence: true

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :order
  has_many :order_items

  default_scope { where(selected: true) }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items

  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/catering_controller.rb
  class CateringController < ApplicationController

    def new
    @catering = Catering.new
   end

 def create
    @catering = Catering.new(catering_params)
    
    if @catering.valid?
      ContactForm.new_catering(@catering).deliver
      render :new
      flash[:alert] = "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end

private

  def catering_params
    params.require(:catering).permit(:name, :email, :message)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
   end

   def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
   end

   def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
   end

   private
   def order_item_params
    params.require(:order_item).permit(:quantity, :item_id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catering_helper.rb
module CateringHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :item_id, value: item.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.item.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', item: order_item.item, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/catering/new.html.erb
<!-- WRAPPER -->
  <div class="wrapper">

    <!-- HOME -->
    <section class="module module-header bg-dark bg-dark-50" data-background="assets/images/section-1.jpg">

      <div class="container">

        <!-- MODULE TITLE -->
        <div class="row">

          <div class="col-sm-6 col-sm-offset-3">

            <h1 class="module-title font-alt align-center">Catering</h1>

            <div class="module-subtitle font-inc align-center">
              Looking for fresh, friendly and professional gourmet catering? Let us know your thoughts, we'll make it happened

            </div>

          </div>

        </div>
        <!-- /MODULE TITLE -->

      </div>

    </section >
    <!-- /HOME -->
    <br/><br/>

				<!-- CONTACT FORM -->
				<div class="row">

					<div class="col-sm-6 col-sm-offset-3">

						<%= simple_form_for @catering, url: contact_path do |message_form| %>
						<form id="contact-form" role="form" novalidate="">

							<div class="form-group">
								<label class="sr-only" for="cname">Name</label>
								<%= message_form.text_field :name, class: 'form-control', id: 'cemail', placeholder: "Name" %>
								<p class="help-block text-danger"></p>
							</div>

							<div class="form-group">
								<label class="sr-only" for="cemail">Your Email</label>
								<%= message_form.email_field :email, class: 'form-control', id: 'cemail', placeholder: 'Your Email Address' %>
								<p class="help-block text-danger"></p>
							</div>

							<div class="form-group">
								<%= message_form.text_area :message, class: 'form-control', id:"cmessage", rows: 7, placeholder: 'Your message here...' %>
								<p class="help-block text-danger"></p>
							</div>

							<%= message_form.submit "Send", class: 'btn btn-round btn-g' %>

						</form>
						<% end %>

						<!-- Ajax response -->
						<div id="contact-response" class="ajax-response font-alt"></div>

					</div>

				</div>
				<!-- /CONTACT FORM -->

			</div>

		</section>
		<!-- /CONTACT -->

		<!-- DIVIDER -->
		<hr class="divider-w">
		<!-- /DIVIDER -->

                    <!-- CONTACT -->
    <section class="module-small">
    
      <div class="container">
    
        <div class="row">
    
          <!-- CONTENT BOX -->
          <div class="col-sm-6">
            <div class="content-box">
              <div class="content-box-title font-inc">
                59-61 Gertrude St, Fitzroy
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
  
    
          <!-- CONTENT BOX -->
          <div class="col-sm-6">
            <div class="content-box">
              <div class="content-box-title font-inc">
                hello@mightyboyeatery.com.au
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
        </div>
    
      </div>
    
    </section>
    <!-- /CONTACT -->

    <!-- FOOTER -->
    <footer class="footer">
    
      <div class="container">
    
        <div class="row">
    
          <div class="col-sm-12 text-center">
            <p class="copyright font-inc m-b-0">© 2016 <a href="index.html">A Macia</a>, All Rights Reserved.</p>
          </div>
    
        </div>
    
      </div>
    
    </footer>
    <!-- /FOOTER -->

</body>
</html>

app/views/contact_form/contact_email.html.erb
<p>Hey There!</p>
<p>
    Congrats!  <b>A catering order has been made</b>
</p>


app/views/contact_form/new_catering.text.erb
<%= @catering.name %> <<%= @catering.email %>> wrote:

<%= @catering.message %>

app/views/items/_items_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= item.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/items/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @items.each do |item| %>
      <%= render "items_row", item: item, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Mightyboy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <!-- PRELOADER -->
  <div class="page-loader">
    <div class="loader">Loading...</div>
  </div>
  <!-- /PRELOADER -->

  <!-- NAVIGATION -->
  <nav class="navbar navbar-custom navbar-transparent navbar-fixed-top" role="navigation">

      <div class="container">
    
        <div class="navbar-header">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#custom-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Mighty Boy Eatery', root_path, class: 'navbar-brand' %>
        </div>
    
        <div class="collapse navbar-collapse" id="custom-collapse">
    
          <ul class="nav navbar-nav navbar-right">
    
            <li>
              <a class="nav navbar-nav navbar-right" <%= link_to 'home', root_path, class: 'navbar-brand' %></a>
            </li>
    
    
            <li>
              <a class="nav navbar-nav navbar-right" <%= link_to 'catering', catering_path, class: 'navbar-brand' %></a>
            </li>
    
          </ul>
        </div>
    
      </div>

  </nav>
  <!-- /NAVIGATION -->

<div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>

<%= yield %>

</body>
</html>

app/views/orders/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/orders/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/orders/new.html.erb
<!-- WRAPPER -->
  <div class="wrapper">

    <!-- HOME -->
    <section class="module module-header bg-dark bg-dark-50" data-background="assets/images/section-1.jpg">

      <div class="container">

        <!-- MODULE TITLE -->
        <div class="row">

          <div class="col-sm-6 col-sm-offset-3">

            <h1 class="module-title font-alt align-center">Orders / Pick-up</h1>

            <div class="module-subtitle font-inc align-center">
              Order now - Pay later
            </div>

          </div>

        </div>
        <!-- /MODULE TITLE -->

      </div>

    </section >
    <!-- /HOME -->

<body>
    <!-- -->
    <section class="module-small p-t-20">

      <div class="container">

            <!-- FILTER -->
        <div class="row">
          <div class="col-sm-12">

            <ul id="filters" class="filter font-inc hidden-xs">
              <li><a href="#" data-filter="*" class="current wow fadeInUp">All</a></li>
              <li><a href="#" data-filter=".breakfast" class="wow fadeInUp" data-wow-delay="0.2s">Breakfast</a></li>
              <li><a href="#" data-filter=".lunch" class="wow fadeInUp" data-wow-delay="0.4s">Lunch</a></li>
              <li><a href="#" data-filter=".drinks" class="wow fadeInUp" data-wow-delay="0.6s">Drinks</a></li>
            </ul>

          </div>
        </div>


        <!--- FILTER -->

        <br />


        <!-- LIST -->
        <ul id="works-grid" class="works-grid works-grid-4 works-hover-w">

          <!-- ITEM -->
          <li class="work-item breakfast">
              <div class="work-image">
                <%= image_tag 'bennie.jpg', class: 'img-responsive' %>
              </div>
              <br />
              <div class="work-caption">
                <h3 class="work-title font-alt">Sirracha Eggs Benedict</h3>
                <div class="work-descr font-inc">
                  blablabla
                </div>
                <!-- Button trigger modal -->
                <br />
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                   Add to Cart
                  </button>
              </div>
            </a>
          </li>
          <!--- ITEM -->

          <!-- ITEM -->
          <li class="work-item breakfast">
              <div class="work-image">
                <%= image_tag 'brie.jpg', class: 'img-responsive' %>
              </div>
              <div class="work-caption">
                <br />
                <h3 class="work-title font-alt">Brie & Cumin Hash</h3>
                <div class="work-descr font-inc">
                  blablabla
                </div>
                <br />
                <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                   Add to Cart
                  </button>
              </div>
            </a>
          </li>
          <!--- ITEM -->

          <!-- ITEM -->
          <li class="work-item lunch">
              <div class="work-image">
                <%= image_tag 'baguette.jpg', class: 'img-responsive' %>
              </div>
              <div class="work-caption">
                <br />
                <h3 class="work-title font-alt">Bahn Mi</h3>
                <div class="work-descr font-inc">
                  blablabla
                </div>
                <br />
                <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                   Add to Cart
                  </button>
              </div>
            </a>
          </li>
          <!--- ITEM -->

          <!-- ITEM -->
          <li class="work-item breakfast">
              <div class="work-image">
                <%= image_tag 'muesli.jpg', class: 'img-responsive' %>
              </div>
              <div class="work-caption">
                <br />
                <h3 class="work-title font-alt">Soy yogurt & Muesli</h3>
                <div class="work-descr font-inc">
                  blablabla
                </div>
                <br />
                <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                   Add to Cart
                  </button>
              </div>
            </a>
          </li>
          <!--- ITEM -->

          <!-- ITEM -->
          <li class="work-item lunch">
              <div class="work-image">
                <%= image_tag 'ricebowl.jpg', class: 'img-responsive' %>
              </div>
              <div class="work-caption">
                <br />
                <h3 class="work-title font-alt">Rice Bowl</h3>
                <div class="work-descr font-inc">
                  blablabla
                </div>
                <br />
                <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                   Add to Cart
                  </button>
              </div>
            </a>
          </li>
          <!--- ITEM -->

          <!-- ITEM -->
          <li class="work-item breakfast">
              <div class="work-image">
                <%= image_tag 'chilli_scrambled.jpg', class: 'img-responsive' %>
              </div>
              <div class="work-caption">
                <br />
                <h3 class="work-title font-alt">Chilli scrambled Eggs</h3>
                <div class="work-descr font-inc">
                  blablabla
                </div>
                <br />
                <!-- Button trigger modal -->
                  <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                   Add to Cart
                  </button>
              </div>
            </a>
          </li>
          <!--- ITEM -->

        </ul>
        <!--- LIST -->

      </div>

    </section>
    <!--- -->

    <!-- /POST -->

        <div class="row">

          <div class="col-sm-8 col-sm-offset-2">

            <!-- POST -->
            <div class="post">

              <div class="post-header">
                <h1 class="post-title font-alt text-center"><a href="blog-single.html">Your Order</a></h1>
              </div>

              <div class="post-entry">

              </div>

            </div>

          </div>

        </div>
            <!-- /POST -->

                    <!-- CONTACT -->
    <section class="module-small">
    
      <div class="container">
    
        <div class="row">
    
          <!-- CONTENT BOX -->
          <div class="col-sm-6">
            <div class="content-box">
              <div class="content-box-title font-inc">
                59-61 Gertrude St, Fitzroy
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
  
    
          <!-- CONTENT BOX -->
          <div class="col-sm-6">
            <div class="content-box">
              <div class="content-box-title font-inc">
                hello@mightyboyeatery.com.au
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
        </div>
    
      </div>
    
    </section>
    <!-- /CONTACT -->


</body>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add to cart</h4>
      </div>
      <div class="modal-body">
        blablabla
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/orders/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/static_pages/index.html.erb
  <!-- HOME -->
  <section id="home" class="module-hero module-parallax module-fade module-full-height bg-dark-30" data-background="assets/images/logo.jpg">
    <div class="hs-caption container">
      <div class="caption-content">
        <div class="hs-title-size-1 font-inc">
          <%= image_tag 'logo.jpg', class: 'img-responsive' %>
        </div>
      </div>
    </div>

  </section >
  <!-- /HOME -->

	<!-- WRAPPER -->
	<div class="wrapper">

		<!-- PORTFOLIO -->
		<section class="module-small p-t-20 p-b-60">

			<div class="container">

				<!-- PORTFOLIO LIST -->
				<ul id="works-grid" class="works-grid works-grid-gut works-grid-2 works-hover-w">

					<!-- PORTFOLIO ITEM -->
					<li class="work-item illustration webdesign">
						<%= link_to catering_path do %>
							<div class="work-image">
								<%= image_tag 'order.jpg', class: 'img-responsive' %>
							</div>
							<% end %>
							<div class="work-caption">
								<h3 class="work-title font-alt">Catering</h3>
							</div>
						</a>
					</li>
					<!-- /PORTFOLIO ITEM -->

					<!-- PORTFOLIO ITEM -->
					<li class="work-item marketing webdesign">
							<div class="work-image">
								<%= image_tag 'catering.jpg', class: 'img-responsive' %>
							</div>
							<div class="work-caption">
								<h3 class="work-title font-alt">Order / Pick-up</h3>
								 <div class="work-descr font-inc">
                  COMING SOON !
                </div>
							</div>
						</a>
					</li>
					<!-- /PORTFOLIO ITEM -->

				</ul>
				<!-- /PORTFOLIO LIST -->

			</div>

		</section>
		<!-- /PORTFOLIO -->

	</div>
	<!-- /WRAPPER -->
	      <!-- CONTACT -->
    <section class="module-small">
    
      <div class="container">
    
        <div class="row">
    
          <!-- CONTENT BOX -->
          <div class="col-sm-6">
            <div class="content-box">
              <div class="content-box-title font-inc">
                59-61 Gertrude St, Fitzroy
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
          <!-- CONTENT BOX -->
          <div class="col-sm-6">
            <div class="content-box">
              <div class="content-box-title font-inc">
                hello@mightyboyeatery.com.au
              </div>
            </div>
          </div>
          <!-- /CONTENT BOX -->
    
        </div>
    
      </div>
    
    </section>
    <!-- /CONTACT -->

    <!-- FOOTER -->
    <footer class="footer">
    
      <div class="container">
    
        <div class="row">
    
          <div class="col-sm-12 text-center">
            <p class="copyright font-inc m-b-0">© 2016 <a href="index.html">Mighty Boy</a>, All Rights Reserved.</p>
          </div>
    
        </div>
    
      </div>
    
    </footer>
    <!-- /FOOTER -->
